app/__init__.py
from config import DevelopmentConfig, ProductionConfig
from flask import Flask, render_template, request
import os

from flask_limiter import Limiter

limiter = Limiter(key_func=lambda: request.remote_addr)

from flask_wtf.csrf import CSRFProtect

csrf = CSRFProtect()

from flask_marshmallow import Marshmallow

marshmallow = Marshmallow()


def create_app():
    app = Flask(__name__)

    env = os.getenv("FLASK_ENV", "development")

    config_class = ProductionConfig if env == "production" else DevelopmentConfig
    app.config.from_object(config_class)

    config_class.init_app(app)
    limiter.init_app(app)
    csrf.init_app(app)
    marshmallow.init_app(app)

    from app.errors import error_handlers
    app.register_blueprint(error_handlers.errors)

    from app.management import routes as management_routes
    app.register_blueprint(management_routes.management_bp)

    from app.auth import routes as auth_routes
    app.register_blueprint(auth_routes.authen)

    from app.home import routes as home_routes
    app.register_blueprint(home_routes.home_bp)

    @app.route('/')
    def main():
        return render_template('main/index.html')

    return app

app/home/__init__.py
from flask import Blueprint

home_bp = Blueprint('home_bp', __name__)

app/home/routes.py
from flask import render_template, jsonify

from . import home_bp
from app.utils.create_map import bus_setup

@home_bp.route('/home/api/assignments')
def get_assignments():
    assigned_data = bus_setup()
    return jsonify(assigned_data)

@home_bp.route('/home')
def home():
    return render_template('home/index.html')

@home_bp.route('/form')
def form():
    return render_template('form/index.html')

app/management/__init__.py
from flask import Blueprint

management_bp = Blueprint('management_bp', __name__)

app/management/routes.py
from functools import wraps
from flask import redirect, render_template, session, url_for, request, jsonify

from . import manage
from . import management_bp

from app.utils import create_map


def login_required(f):
    @wraps(f)
    def access_control(*args, **kwargs):
        if 'loggedin' not in session:
            return redirect(url_for('authen.auth'))
        if kwargs.get('username') and session.get('name') != kwargs.get('username'):
            return redirect(url_for('authen.auth'))
        return f(*args, **kwargs)

    return access_control


@management_bp.route('/management/api/undo_assignments', methods=['POST'])
def undo_assignments():
    data = request.get_json()
    bus_name = data.get('bus_name')
    spot_name = data.get('spot_name')

    return manage.undo_selection(bus_name, spot_name)


@management_bp.route('/management/api/assignments')
def get_assignments():
    assigned_data = create_map.bus_setup()

    return jsonify(assigned_data)


@management_bp.route('/management/<username>', methods=['GET', 'POST'])
@login_required
def management(username):
    if 'loggedin' not in session:
        return redirect(url_for('authen.auth'))

    available_options, parking_spots = manage.get_available_data()

    if request.method == 'POST':
        selected_bus = request.form.get('bus_selector')
        selected_spot = request.form.get('spot_selector')

        if not selected_bus or not selected_spot:
            msg = "Please select both a bus and a parking spot."
            session['msg'] = msg
            return redirect(url_for('management_bp.management', username=username))

        else:
            msg = manage.process_selection(selected_bus, selected_spot)
            session['msg'] = msg
            return redirect(url_for('management_bp.management', username=username))

    msg = session.pop('msg', '')

    print(f"Current options passed to template: {available_options}, Parking spots: {parking_spots}")

    return render_template('management/index.html', username=username, options=available_options, spots=parking_spots,
                           msg=msg)

app/templates/_macros.html
{% macro head() -%}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <title>NBTHS BUSAPP</title>
{%- endmacro %}

{% macro navbar() -%}
    <nav class="navbar navbar-expand-lg bg-success">
        <div class="container">
            <a class="navbar-brand text-white" href="{{ url_for('home_bp.home') }}">NBTHS BusApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('authen.auth') }}" class="">Manage</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('home_bp.home') }}" class="">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white" href="{{ url_for('home_bp.form') }}" class="">Late Bus</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{%- endmacro %}

app/templates/form/index.html
{% extends 'layout.html' %}

{% block content %}
    {{ macros.navbar() }}
    <div class="d-flex justify-content-center">
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdk01zDDyYaTRzAlAB76RWjYuuPXeSc6LWsjh71thJTsE4CxA/viewform?embedded=true" width="640" height="987" frameborder="0" marginheight="0" marginwidth="0", scrolling="no">Loading…</iframe>
    </div>
{% endblock %}

app/templates/home/index.html
{% extends 'layout.html' %}

{% block content %}
    {{ macros.navbar() }}
    <div class="mt-4" id="assignments-container"></div>
    <script src="{{url_for('static', filename='javascript/home.js')}}"></script>
{% endblock %}

app/templates/layout.html
{% import "_macros.html" as macros %}
<!DOCTYPE html>
<html lang="en">
<head>
    {{ macros.head() }}
</head>
    <body>

        {% block content %}{% endblock %}
    </body>
</html>

app/templates/main/index.html
{% extends 'layout.html' %}

{% block content %}
    <body>
        <div>
            <a href="{{ url_for('authen.auth')}}">Manage</a>
            <a href="{{ url_for('home_bp.home') }}">Home</a>
            <a href="{{ url_for('home_bp.form') }}">Late Bus</a>
        </div>
    </body>
{% endblock %}

app/templates/management/index.html
{% extends 'layout.html' %}

{% block content %}
    {{ macros.navbar() }}
    <div class="mt-4">
        <h2>Welcome, {{username}}</h2>
        <a class="text-blue-500 underline" href="{{url_for('authen.logout')}}">Logout</a>
        {% if session['loggedin'] %}
                <p>{{ msg }}</p>

                <form method="POST" action="{{ url_for('management_bp.management', username=username) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <label for="bus_selector">Choose a Bus:</label>
                    <select name="bus_selector" id="bus_selector" required>
                        {% for option in options %}
                        <option value="{{ option }}">{{ option }}</option>
                        {% endfor %}
                    </select>

                    <label for="spot_selector">Choose a Parking Spot:</label>
                    <select name="spot_selector" id="spot_selector" required>
                        {% for spot in spots %}
                        <option value="{{ spot }}">{{ spot }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit">Submit</button>
                </form>
                <div id="undo-assignments-container"></div>
            <script src="{{url_for('static', filename='javascript/manage.js')}}"></script>
        {% endif %}
    </div>
{% endblock %}